apiVersion: v2
name: argocd-wrapper-chart
description: ArgoCD wrapper Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: argo-cd
    version: 5.23.2
    repository: https://argoproj.github.io/argo-helm
